"""Memory cache for LLM outputs."""

from __future__ import annotations

import hashlib
import json
import time
from collections import OrderedDict
from typing import Any

from app.config import Settings


class TTLCache:
    """An LRU cache with time-to-live semantics for LLM responses.

    Keys are generated by taking the SHA-256 hash of a canonical JSON array:
    [PROMPT_VERSION, model, task, masked texts, options]
    """

    def __init__(self, settings: Settings, clock: Any = time.time) -> None:
        self._max_entries = settings.cache_max_entries
        self._ttl = settings.cache_ttl_seconds
        self._clock = clock
        self._cache: OrderedDict[str, tuple[float, Any]] = OrderedDict()

    def _generate_key(
        self,
        prompt_version: str,
        model: str,
        task: str,
        masked_text: str,
        options: dict[str, Any] | None = None,
    ) -> str:
        if options is None:
            options = {}
        # Ensure dict keys are ordered so JSON is canonical
        ordered_options = {k: options[k] for k in sorted(options.keys())}
        canonical_array = [prompt_version, model, task, masked_text, ordered_options]
        canonical_json = json.dumps(canonical_array, separators=(",", ":"))
        return hashlib.sha256(canonical_json.encode("utf-8")).hexdigest()

    def get(
        self,
        prompt_version: str,
        model: str,
        task: str,
        masked_text: str,
        options: dict[str, Any] | None = None,
    ) -> Any | None:
        """Retrieve a value if it exists and hasn't expired."""
        key = self._generate_key(prompt_version, model, task, masked_text, options)
        if key not in self._cache:
            return None

        expiry, value = self._cache[key]
        if self._clock() > expiry:
            del self._cache[key]
            return None

        # Move to end to mark as recently used
        self._cache.move_to_end(key)
        return value

    def set(
        self,
        prompt_version: str,
        model: str,
        task: str,
        masked_text: str,
        value: Any,
        options: dict[str, Any] | None = None,
    ) -> None:
        """Store a value with TTL."""
        key = self._generate_key(prompt_version, model, task, masked_text, options)
        expiry = self._clock() + self._ttl

        if key in self._cache:
            self._cache.move_to_end(key)
        self._cache[key] = (expiry, value)

        # Evict oldest if we exceeded max_entries
        if len(self._cache) > self._max_entries:
            self._cache.popitem(last=False)
